server {
    listen 80;

    location = /calcolatore-finanze {
        return 301 $scheme://$host$request_uri/;
    }

    location /calcolatore-finanze/ {
        root /var/www;
        index index.html;
        try_files $uri $uri/ /calcolatore-finanze/index.html;
    }

    location = /calcolatore-tasse {
        return 301 $scheme://$host$request_uri/;
    }

    location /calcolatore-tasse/ {
        root /var/www;
        index index.html;
        try_files $uri $uri/ /calcolatore-tasse/index.html;
    }
}
